import streamlit as st
import aerospike
from aerospike import predicates as p
import google.generativeai as genai
import os, uuid, re, time
from dotenv import load_dotenv
from google.api_core import retry, exceptions

# 1. SETUP & CONFIG
load_dotenv()
genai.configure(api_key=os.getenv("GEMINI_API_KEY"))
model = genai.GenerativeModel('gemini-2.5-flash')

# 2. ROBUST AEROSPIKE CONNECTION (With Retry)
@st.cache_resource
def get_aerospike_client():
    host = os.getenv("AEROSPIKE_HOST", "aerospike")
    port = 3000
    
    # Simple retry loop for Docker startup race conditions
    for i in range(5):
        try:
            client = aerospike.client({'hosts': [(host, port)]}).connect()
            return client
        except Exception as e:
            time.sleep(2)
            if i == 4: st.error(f"Could not connect to Aerospike: {e}")
    return None

client = get_aerospike_client()

# 3. SETUP: Create Secondary Index
if client:
    try:
        client.index_string_create('test', 'recipes', 'island', 'island_idx')
    except:
        pass # Index already exists

# 4. UTILITY: Fix the "island Bug" by parsing the AI output
def extract_island(text):
    """Parses 'Origin: IslandName' from the AI response."""
    match = re.search(r"Origin:\s*([\w\s]+)", text)
    if match:
        return match.group(1).strip()
    return "Unknown"

# --- UI START ---
st.set_page_config(page_title="Caribbean AI Kitchen", page_icon="🌴")
st.title("🌴 Caribbean AI Kitchen")

# Sidebar Search
islands = ["All", "Jamaica", "Trinidad", "Haiti", "Cuba", "Puerto Rico", "Dominican Republic"]
filter_choice = st.sidebar.selectbox("Filter by Island:", islands)

pantry = st.text_input("Ingredients on hand (e.g., 'plantains, saltfish, scotch bonnet'):")

# 5. GENERATE & SAVE LOGIC
if st.button("Generate & Save"):
    if not pantry:
        st.warning("Please enter some ingredients first!")
    else:
        with st.spinner("The chef is cooking..."):
            try:
                # Wrap in retry for Quota 429 errors
                @retry.Retry(predicate=retry.if_exception_type(exceptions.ResourceExhausted))
                def call_gemini():
                    prompt = f"Expert Caribbean chef: Create a recipe with {pantry}. Start with 'Origin: [Island Name]'."
                    return model.generate_content(prompt).text
                
                res = call_gemini()
                
                # BUG FIX: Extract the actual island generated by the AI
                island_tag = extract_island(res)
                
                # Save to Aerospike
                key = ('test', 'recipes', str(uuid.uuid4()))
                client.put(key, {'island': island_tag, 'content': res})
                
                st.success(f"Recipe saved under {island_tag}!")
                st.markdown(res)
                
            except Exception as e:
                st.error(f"Error: {e}")

st.divider()

# 6. QUERY LOGIC (Fixed for Indexing)
st.subheader(f"Saved {filter_choice} Recipes")
if client:
    try:
        query = client.query('test', 'recipes')
        if filter_choice != "All":
            query.where(p.equals('island', filter_choice))
        
        records = query.results()
        if not records:
            st.write("No recipes found for this selection.")
        else:
            for r in records:
                # r[2] contains the bins (bins['content'])
                with st.expander(f"Recipe from {r[2].get('island', 'Unknown')}"):
                    st.write(r[2].get('content'))
    except Exception as e:
        st.error("Make sure the Secondary Index is ready. You might need to generate one recipe first.")
